apiVersion: ENC[AES256_GCM,data:V0o=,iv:pe/N2hE4dqjnEJaK+FLo4cRbLbImClklRP4SLCox6Nc=,tag:lvJu/8RumHQnpXxsXLke/g==,type:str]
kind: ENC[AES256_GCM,data:nR9MlDV4,iv:C3uIIge+Rl739qMpjij4cvEn9mM1Z+DPKpNmPeFCmrk=,tag:6IutbizNh9b8h8SJSW4SSQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vfpt+ClMJoP2dzX//s0IdG0S0w==,iv:X4tZTgjAtoRnJymtBbx5b717N4ReQgEWNbrg+jHfWcc=,tag:Zk+xzAES3OMgQrO4nHl2kw==,type:str]
type: ENC[AES256_GCM,data:Fo5PeG70,iv:+qJdqTN7/Cjp8aNwbwUcQEUsO87lUUj+pN29IlqVm04=,tag:cgDIPa9YYjytkKarlui/pw==,type:str]
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:CalQOoj7yW0=,iv:u67dhuFeWm+eOErDoXeP0NU55ijGtLXvZzlgHAEhJro=,tag:S82T/K5VifHjiEMv89f8+g==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:nMJcGyxqwRVfJQ==,iv:29wRYC1NR/OWjQY2cVwk4NJwpzmx4QtmsC2KUOrRxT4=,tag:YCuwuTqIV69j7r6hCxDK0g==,type:str]
    JWT_SECRET_KEY: ENC[AES256_GCM,data:cNClY/xRwYU34ao=,iv:W6bOCcUYTyaLz6Yp//L6hG2CEE06JJtE1JLmGzKUL7M=,tag:2ArS0y3KEmbs5czRZcQGgQ==,type:str]
    JWT_REFERSH_SECRET_KEY: ENC[AES256_GCM,data:Fog76yw4ESYrpBbP,iv:EcIgKLHDvYCJEu/aGnFXj4e6hCxPxIEY9oCarVvHspc=,tag:/3jF92uOQr46LIHj2urd5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-03-14T20:44:39Z"
    mac: ENC[AES256_GCM,data:DpapU0ZVJ2l/yMZtOHvRnyKsQ49/na8V1dWHW1AbpGxPnmTnAeduXfIGEuv6L/cWFWe2qeaeKz2K56kYadjzkNtBZfVio/dzbbG5qg6l8l0SqhY7aA97TJZWcDwHWXigmXpQmDyNIOwLHgabOs729fcTk0N4Fom2Dh8xW//vVS4=,iv:SJfozE8QgEn4ZQjGi6R0NjsxPnYWSQ0xwXikjVMfEL0=,tag:VOGsvUhEZM7iLmRjUP81Mw==,type:str]
    pgp:
        - created_at: "2024-03-14T20:44:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA+p1nx4UpjgEAQwAslOSrGPf29lnm7iKqX5HtltTBsDAVyksxAmoXhvKZ0Me
            Vku0jZz+3KcCmvoZTeiUlRylmmJztNUDI8G27oORHZxijqF+6ZtSdEJ96hvjmNYi
            QeWKNgDF2toWpLfOsjTKxgDJ2QYDhiw9goMRrbKh63e14MQV0V6Vbjfocus2FIof
            lQz6w/05CtfRysPhUKzk8dhj9B+VtFPDttMIbYexVuNAASitj4gpP9iWtPwLs0us
            uAF6825HlXHwonlAr3q+cwUIGdUGcTznxxZcqsVzhdHE/OpGr5meOt/D7npa3Esj
            D/qiWJ44FWZ3lyIzt7lhvjcQyx3RNBbwwyqNhyPNwoJZlND0hly+GDvRKzO2qdyS
            8gxtBs5SNKYliL4rUe3bNJZ/bpY7cmab1EdgmoKzFZO23MCfEg9Ut8DShSATaH9v
            BQyZFOLly/5/5mI5j1NDYB/dK+jXac70JCjxJy9s2RcUmh/n9TFqw+O3smm6DHpr
            9YndaX5qGGFWktpGxLFT1GgBCQIQAoTFY8zb2Trd9JYRyK/AF26pXAsb+AP+mXmh
            nBMcxFRWTKK/cbaSQdmZvYiAA62ijLucfMufcs6Px4wFoD5YfWiGt8H2dSpowGOv
            895osVoZw62EH5IVO0FRoY628LzmIDnDVg==
            =Q+wQ
            -----END PGP MESSAGE-----
          fp: 0BCAAA75A9A5FF08577645582D0C80B71AEF6288
    unencrypted_suffix: _unencrypted
    version: 3.8.1
