# Generated by Django 4.2.2 on 2024-03-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_alter_task_options"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="task",
            name="valid_status",
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNASSIGNED", "Unassigned"),
                    ("IN_PROGRESS", "In Progress"),
                    ("DONE", "Done"),
                    ("ARCHIVED", "Archived"),
                ],
                db_comment="Can be UNASSIGNED, IN PROGRESS, DONE, or ARCHIVED",
                default="UNASSIGNED",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                check=models.Q(("status__in", ["UNASSIGNED", "IN_PROGRESS", "DONE", "ARCHIVED"])), name="valid_status"
            ),
        ),
    ]
